# Generated by Django 5.0 on 2025-10-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('city_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_favorite', '-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='core_locati_user_id_94fed0_idx'), models.Index(fields=['latitude'], name='core_locati_latitud_43ae9d_idx'), models.Index(fields=['longitude'], name='core_locati_longitu_622b06_idx')],
                'unique_together': {('user_id', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('temperature_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='C', max_length=1)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_data', models.JSONField(default=dict)),
                ('forecast_data', models.JSONField(blank=True, null=True)),
                ('cache_type', models.CharField(choices=[('current', 'Current'), ('forecast', 'Forecast')], max_length=10)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caches', to='core.location')),
            ],
            options={
                'ordering': ['-cached_at'],
                'indexes': [models.Index(fields=['location'], name='core_weathe_locatio_33f57a_idx'), models.Index(fields=['cached_at'], name='core_weathe_cached__9b99e1_idx'), models.Index(fields=['cache_type'], name='core_weathe_cache_t_3de75a_idx')],
            },
        ),
    ]
